### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by bdwain** [coatue-oss/angular2react#17]
Hi. Thanks for the helpful library. I think there's a few issues with the package.json dependencies.

- React, React Dom, and Angular should be peer dependencies, not regular dependencies. Libraries should not dictate the versions of code that an app is expected to import because then conflicting versions will happen. Since no one would ever use this without already having all of these libraries, they can be safely moved to peer dependencies.
- React 15 support was dropped even though it would still work. There's not much reason to drop support for 15 if you are not using portals or componentDidCatch. React 16 hasn't been out too long and a lot of people are still on 15 while bugs are being ironed out (I'm personally waiting on an enzyme bugfix before I upgrade to react 16 because the old enzyme does not support it). If react and react-dom were moved to peer dependencies, the semver could allow both 15 and 16.
- The @types packages should be dev dependencies, not regular dependencies.

I can make a PR to address them if you are open to making these changes.

**Comment by bcherny** [comment]
All of these sound good to me - awaiting your PR!

**Comment by bdwain** [comment]
#18 is made!

**Comment by bcherny** [comment]
`+ angular2react@2.1.1`

**Comment by bdwain** [comment]
thanks for fixing that so quickly!
