### ISSUE TITLE
Seeing `angular2react@2.2.0 requires a peer of react@^>=15.0.0 but none is installed` warning

### ISSUE THREAD

**Issue by sanduteo95** [coatue-oss/angular2react#26]
The `package.json` mentions react as a peer dependency, but the syntax might be incorrect.
```
  "peerDependencies": {
    "angular": ">=1.5.0",
    "react": "^>=15.0.0", ---> `>=15.0.0` instead of `^>=15.0.0` 
    "react-dom": ">=15.0.0"
  }
```
`^15.0.0` is equivalent to `>=15.0.0 <16.0.0`
`>=15.0.0` is equivalent to `>=15.0.0`
So `^>15.0.0` doesn't make much sense.
 
When I try to install the dependencies in my project and in the https://github.com/bcherny/angular2react-demos project I see the following: 
`npm WARN angular2react@2.2.0 requires a peer of react@^>=15.0.0 but none is installed. You must install peer dependencies yourself.`

If I try to list both `angular2react` and `react` I see the following:
```$ npm list angular2react
angular2react-demos@1.0.0 /Users/teodorasandu/Documents/Cloud/angular2react-demos/multi-file
└── angular2react@2.2.0

$ npm list react
angular2react-demos@1.0.0 /Users/teodorasandu/Documents/Cloud/angular2react-demos/multi-file
└── (empty)```
But I can see `react` in the `node_modules`

It looks like react does not get installed properly, and it might be because of the syntax for peer dependencies. Any thoughts?

**Comment by bcherny** [comment]
Good catch @sanduteo95!

Fix is published in 2.2.1. To fix your issue, run `npm install` in your project's folder.
