### ISSUE TITLE
Is there a way to pass a callback with `&`?

### ISSUE THREAD

**Issue by korya** [coatue-oss/angular2react#3]
Is there a way to pass a callback to angular component from react component?

I have an angular component that is a child of react component. The mapping from the parent (react) to the child (angular) works fine with `<` bindings. What I need is the other way communication: from the child (angular) to the parent (react) with '&' bindings. Is there a way to do it?

**Comment by korya** [comment]
When I pass the callback with `&`, the communication from child to parent is broken. However when I pass it with `<` or `=`, it works: the callback provided in react props is being called. The question is how robust this approach is. What do you say?

**Comment by bcherny** [comment]
Hi @korya. Unfortunately, React only supports 1-way bindings (`<`). The idea is to simplify the way data flows by eliminating 2-way bindings (`=`) and expression bindings (`&`).

Expression bindings are really a type of 1-way binding. You can update your code to use `<` bindings instead. For example:

```html
// before
<component onClick="onClick(value)"></component>

// after
<component onClick="onClick"></component>
```

I hope that helps!

**Comment by korya** [comment]
OK. Thanks.
