### ISSUE TITLE
Angular 1.6 requirement?

### ISSUE THREAD

**Issue by jrsquared** [coatue-oss/angular2react#6]
There are quite a few projects around here that are on angular 1.5 and want to convert slowly to React using angular2react. It would be great to not have to upgrade to 1.6 before migrating to react.

Is there a reason this project requires angular 1.6, or would it be happy with `1.5.x || 1.6.x`?

**Comment by bcherny** [comment]
Hi @jrsquared! >=1.5.0 should be fine - we just need support for the Component API. PRs are welcome.

**Comment by bcherny** [comment]
Published 2.0.3.
