### ISSUE TITLE
Does it work with Angular 1.6 Directives as well?

### ISSUE THREAD

**Issue by nikhilgarg789** [coatue-oss/angular2react#9]

**Comment by bcherny** [comment]
It works with components, at any Angular version. Maybe we can add directive support sometime in the future, but it's not straight forward. If you want to take a shot at it, PRs are welcome!

**Comment by nikhilgarg789** [comment]
Okay..Thanks.

Is there any other way / hack I can use my current angular directive inside react app? Like maybe wrapping my directive in a component?

**Comment by bcherny** [comment]
Yeah, you can definitely do that. All components work for angular2react, doesn't matter what they contain (directives, other components, etc.).
